### PR TITLE
Feature/patients

### PR DESCRIPTION
**Pull request by ChristineAkinyi**
# Engineers Checklist

This PR is for merging the feature/patients to dev which contains patient registration and patients functionality.

## Type of change

Specify the kind of PR/MR

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Optimization
- [x] Improvement
- [ ] Bug fix

## How can it be tested?
- Please provide step-by-step guide on how to test
- If web or mobile, screenshots will be very helpful in addition

# Where is it documented?
- List JIRA [tickets]
(https://kamondiagnesauma-1723202712527.atlassian.net/browse/SCRUM-160?atlOrigin=eyJpIjoiNjgyODM4ZWUwNjNlNDdjMTk2NzgyZjZmMDBkZmZjZGUiLCJwIjoiaiJ9)

### CODE REVIEW

**Review by queen-bellah — DISMISSED** [review]

**Comment by ChristineAkinyi** [comment]
Screenshot from 2024-09-20 16-35-09

**Review by Wachira-glory — DISMISSED** [review]

**Review by Agnes-Kamondi — DISMISSED** [review]

**Review by priscilla-mikisa — APPROVED** [review]

**Review by Mary-Njiru — DISMISSED** [review]

**Review by priscilla-mikisa — DISMISSED** [review]

**Review by Agnes-Kamondi — DISMISSED** [review]

**Review by queen-bellah — DISMISSED** [review]

**Review by Mary-Njiru — APPROVED** [review]

**Review by Mary-Njiru — DISMISSED** [review]

**Review by Wachira-glory — APPROVED** [review]

**Review by Agnes-Kamondi — APPROVED** [review]

**Review by priscilla-mikisa — APPROVED** [review]

**Review by hunterachieng — APPROVED** [review]

**Pull request merged**
